/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Address = IDL.Record({
  'zip' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
});
export const Time = IDL.Int;
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'isPremium' : IDL.Bool,
  'name' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addAdmin' : IDL.Func([IDL.Text], [], []),
  'getAllContactInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'whatsapp' : IDL.Opt(IDL.Text),
          'facebook' : IDL.Opt(IDL.Text),
          'address' : IDL.Opt(Address),
          'adminEmails' : IDL.Vec(IDL.Text),
          'phone' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], []),
  'getContactInfo' : IDL.Func(
      [],
      [
        IDL.Record({
          'whatsapp' : IDL.Opt(IDL.Text),
          'facebook' : IDL.Opt(IDL.Text),
          'address' : IDL.Opt(Address),
          'phone' : IDL.Opt(IDL.Text),
        }),
      ],
      ['query'],
    ),
  'markAsPremium' : IDL.Func([IDL.Nat], [], []),
  'removeAdmin' : IDL.Func([IDL.Text], [], []),
  'submitInquiry' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Bool], [], []),
  'updateContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Address], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Address = IDL.Record({
    'zip' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
  });
  const Time = IDL.Int;
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'isPremium' : IDL.Bool,
    'name' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addAdmin' : IDL.Func([IDL.Text], [], []),
    'getAllContactInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'whatsapp' : IDL.Opt(IDL.Text),
            'facebook' : IDL.Opt(IDL.Text),
            'address' : IDL.Opt(Address),
            'adminEmails' : IDL.Vec(IDL.Text),
            'phone' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], []),
    'getContactInfo' : IDL.Func(
        [],
        [
          IDL.Record({
            'whatsapp' : IDL.Opt(IDL.Text),
            'facebook' : IDL.Opt(IDL.Text),
            'address' : IDL.Opt(Address),
            'phone' : IDL.Opt(IDL.Text),
          }),
        ],
        ['query'],
      ),
    'markAsPremium' : IDL.Func([IDL.Nat], [], []),
    'removeAdmin' : IDL.Func([IDL.Text], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Address], [], []),
  });
};

export const init = ({ IDL }) => { return []; };