/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'zip' : string,
  'street' : string,
  'country' : string,
  'city' : string,
}
export interface Inquiry {
  'id' : bigint,
  'isPremium' : boolean,
  'name' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export type Time = bigint;
export interface _SERVICE {
  'addAdmin' : ActorMethod<[string], undefined>,
  'getAllContactInfo' : ActorMethod<
    [],
    {
      'whatsapp' : [] | [string],
      'facebook' : [] | [string],
      'address' : [] | [Address],
      'adminEmails' : Array<string>,
      'phone' : [] | [string],
    }
  >,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getContactInfo' : ActorMethod<
    [],
    {
      'whatsapp' : [] | [string],
      'facebook' : [] | [string],
      'address' : [] | [Address],
      'phone' : [] | [string],
    }
  >,
  'markAsPremium' : ActorMethod<[bigint], undefined>,
  'removeAdmin' : ActorMethod<[string], undefined>,
  'submitInquiry' : ActorMethod<[string, string, string, boolean], undefined>,
  'updateContact' : ActorMethod<[string, string, string, Address], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];