/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Inquiry {
    id: bigint;
    isPremium: boolean;
    name: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export type Time = bigint;
export interface Address {
    zip: string;
    street: string;
    country: string;
    city: string;
}
export interface backendInterface {
    addAdmin(email: string): Promise<void>;
    getAllContactInfo(): Promise<{
        whatsapp?: string;
        facebook?: string;
        address?: Address;
        adminEmails: Array<string>;
        phone?: string;
    }>;
    getAllInquiries(): Promise<Array<Inquiry>>;
    getContactInfo(): Promise<{
        whatsapp?: string;
        facebook?: string;
        address?: Address;
        phone?: string;
    }>;
    markAsPremium(id: bigint): Promise<void>;
    removeAdmin(email: string): Promise<void>;
    submitInquiry(name: string, phone: string, message: string, isPremium: boolean): Promise<void>;
    updateContact(fb: string, whatsapp: string, phone: string, addr: Address): Promise<void>;
}
import type { Address as _Address } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addAdmin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async getAllContactInfo(): Promise<{
        whatsapp?: string;
        facebook?: string;
        address?: Address;
        adminEmails: Array<string>;
        phone?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContactInfo();
                return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContactInfo();
            return from_candid_record_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllInquiries(): Promise<Array<Inquiry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllInquiries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllInquiries();
            return result;
        }
    }
    async getContactInfo(): Promise<{
        whatsapp?: string;
        facebook?: string;
        address?: Address;
        phone?: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactInfo();
                return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactInfo();
            return from_candid_record_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAsPremium(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsPremium(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsPremium(arg0);
            return result;
        }
    }
    async removeAdmin(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async submitInquiry(arg0: string, arg1: string, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitInquiry(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateContact(arg0: string, arg1: string, arg2: string, arg3: Address): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Address]): Address | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    whatsapp: [] | [string];
    facebook: [] | [string];
    address: [] | [_Address];
    adminEmails: Array<string>;
    phone: [] | [string];
}): {
    whatsapp?: string;
    facebook?: string;
    address?: Address;
    adminEmails: Array<string>;
    phone?: string;
} {
    return {
        whatsapp: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.whatsapp)),
        facebook: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.facebook)),
        address: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.address)),
        adminEmails: value.adminEmails,
        phone: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    whatsapp: [] | [string];
    facebook: [] | [string];
    address: [] | [_Address];
    phone: [] | [string];
}): {
    whatsapp?: string;
    facebook?: string;
    address?: Address;
    phone?: string;
} {
    return {
        whatsapp: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.whatsapp)),
        facebook: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.facebook)),
        address: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.address)),
        phone: record_opt_to_undefined(from_candid_opt_n2(_uploadFile, _downloadFile, value.phone))
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
